# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbdd5501fe174ea7c6482ce9af24d5a13d1c9ebf61940999410cfeb8a4aeafcc3c4a45ad7dab785cf497e9ed589a9e884e3b122876abdc397fb37ee269104f5a

test:
  secret_key_base: a67211cf59d36c98aefb299d877d3ceb172407bde3db7fc2673f485f268a48815d1cea6e46a51f2b1293c12c75ebaac6f9e73de87535bfa5706eb537b413ed20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
